version: '3.8'
services:
  app:
    build: .
    ports:
      - "9001:9001"
    environment:
      SP_USERNAME: root
      SP_PASSWORD: 0241585915
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 0241585915
      MYSQL_DATABASE: 'patient'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
