version: '3.8'
services:
  microservice-gateway:
    build:
      context: ./microservice-gateway
      dockerfile: Dockerfile
    ports:
      - "9000:9000"

  microservice-back-patient:
    build:
      context: ./microservice-back-patient
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    environment:
      SP_USERNAME: ${SP_USERNAME}
      SP_PASSWORD: ${SP_PASSWORD}
    depends_on:
      - db

  microservice-front:
    build:
      context: ./microservice-front
      dockerfile: Dockerfile
    ports:
      - "9002:9002"

  microservice-back-note:
    build:
      context: ./microservice-back-note
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    environment:
      SP_USERNAME: ${SP_USERNAME}
      SP_PASSWORD: ${SP_PASSWORD}
    depends_on:
      - mongodb

  microservice-back-diabete:
    build:
      context: ./microservice-back-diabete
      dockerfile: Dockerfile
    ports:
      - "9004:9004"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SP_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${SP_PASSWORD}
      MONGO_INITDB_DATABASE: note
    volumes:
      - mongodb_data:/data/db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${SP_PASSWORD}
      MYSQL_DATABASE: 'patient'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  mongodb_data:
  db_data:

