version: '3.8'
services:
  app:
    build: .
    ports:
      - "9003:9003"
    environment:
      SP_USERNAME: ${SP_USERNAME}
      SP_PASSWORD: ${SP_PASSWORD}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SP_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${SP_PASSWORD}
      MONGO_INITDB_DATABASE: note
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
